repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
        args: ['--remove']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.0
    hooks:
    -   id: reorder-python-imports
        args: ['--py3-plus']
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    -   id: remove-tabs
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
    -   id: pyupgrade
        args: ['--py3-plus']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    -   id: add-trailing-comma
        args: ['--py36-plus']
