language: c
services:
    - docker

matrix:
    include:
        - env: ITEST_TARGET=itest_focal
        - env: ITEST_TARGET=itest_buster
        - env: ITEST_TARGET=itest_tox
        - arch: ppc64le
          env: ITEST_TARGET=itest_buster
        - arch: arm64
          env: ITEST_TARGET=itest_buster
        - arch: s390x
          env: ITEST_TARGET=itest_buster
    allow_failures:
        - arch: ppc64le
          env: ITEST_TARGET=itest_buster
        - arch: arm64
          env: ITEST_TARGET=itest_buster
        - arch: s390x
          env: ITEST_TARGET=itest_buster


script:
   - make "$ITEST_TARGET"

after_script:
   - ci/artifact-upload
